name: search-service
channels:
  - conda-forge
dependencies:
  - fastapi=0.89.1
  - pydantic=1.10.5
  - uvicorn=0.20.0
  - pytorch=1.13.1
  - pip=23.0.1
  - python=3.9
  - numpy=1.23.5
  - transformers=4.27.4